services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload