services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    command: bash