version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py