# fly.toml app configuration file generated for 3d-print-quoter-api on 2025-06-03T12:13:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3d-print-quoter-api'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0 
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
